name: C/C++ CI - Run gtest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make test
      run: make test
    - name: run test
      run: cd build/test && .cube3d_unit_test
