name: C/C++ CI - Run gtest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build test
      run: make -s build
    - name: echo
      run: echo ~ && echo $PWD
    - name: run test
      run: make -s test